### PR TITLE
Added Ctdata.org post

### PR DESCRIPTION
**Pull request by GovInTrenches**
Created post outlining ctdata.org. Not sure why it's still wanting to pull in the Health Data file.

### CODE REVIEW

**Comment by GovInTrenches** [comment]
You know what, I know what the merge conflict is now. @waldoj updated my health data post and I never pulled those changes into mine. So, now it's wanting to put the old changes in. I _think_ that you can just ignore the health data post.

**Comment by waldoj** [comment]
Thank you, Christopher! I'm going to figure out how to get this merged and then publish it. :)

**Comment by GovInTrenches** [comment]
Worst case - I can delete the pull request. Pull the main repo into my repo - the resubmit w/o the conflict 

Christopher Whitaker

(Sent from iPhone)

**Comment by waldoj** [comment]
Done in 4cab5d51e2dfdf526796f19d5f2901f419e14c78, to work around GitHub's inability to automatically merge.

**Pull request closed without merging**
